on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test workflow
        uses: ./
        with:
          account-id: ${{ secrets.YOUTUBE_ID }}
          account-password: ${{ secrets.YOUTUBE_PW }}